#!/usr/bin/env python
"""Confluence Release Page — Create release documentation.

Called by release.yaml GitHub Actions workflow on tag push.

Author: Sherman Lye
Created: 2026-03-16

Usage:
    python scripts/release-confluence.py \
        --version v1.0.0 \
        --product demo-product \
        --release-notes-file /tmp/ai-release-notes.md \
        --space IDEVOPSP
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import urllib.request
from datetime import date


def get_auth_header() -> str:
    """Build Basic auth header from environment variables."""
    email = os.environ.get("ATLASSIAN_EMAIL")
    token = os.environ.get("ATLASSIAN_TOKEN")
    if not email or not token:
        print("ERROR: ATLASSIAN_EMAIL and ATLASSIAN_TOKEN must be set", file=sys.stderr)
        sys.exit(1)
    return "Basic " + base64.b64encode(f"{email}:{token}".encode()).decode()


def read_file(path: str) -> str:
    """Read file contents."""
    with open(path, encoding="utf-8") as f:
        return f.read()


def escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def build_release_page(product: str, version: str, release_notes: str) -> str:
    """Build Confluence storage format HTML for the release page."""
    today = date.today().isoformat()
    escaped_notes = escape_html(release_notes)

    return f"""<h2>Release Summary</h2>
<table>
<tbody>
<tr><th>Product</th><td>{product}</td></tr>
<tr><th>Version</th><td>{version}</td></tr>
<tr><th>Date</th><td>{today}</td></tr>
<tr><th>Deploy Target</th><td>EKS</td></tr>
</tbody>
</table>

<h2>Release Notes</h2>
<ac:structured-macro ac:name="code">
<ac:parameter ac:name="language">markdown</ac:parameter>
<ac:plain-text-body><![CDATA[{release_notes}]]></ac:plain-text-body>
</ac:structured-macro>

<h2>Deployment Details</h2>
<h3>Environments</h3>
<table>
<tbody>
<tr><th>Environment</th><th>Approval</th><th>Status</th></tr>
<tr><td>Dev</td><td>Auto</td><td>Pending</td></tr>
<tr><td>Staging</td><td>Required</td><td>Pending</td></tr>
<tr><td>Production</td><td>Required</td><td>Pending</td></tr>
</tbody>
</table>

<h3>Governance</h3>
<ul>
<li>SAST: Required (SonarQube)</li>
<li>SBOM: Required</li>
<li>Coverage Floor: 80%</li>
<li>Duplication Max: 5%</li>
</ul>

<h2>Rollback Plan</h2>
<ol>
<li>Identify the issue via monitoring dashboards</li>
<li>Run: <code>helm rollback {{release}} {{previous-revision}}</code></li>
<li>Verify health endpoints return 200</li>
<li>Notify stakeholders of rollback</li>
<li>Create post-incident JIRA ticket</li>
</ol>

<h2>Smoke Test Checklist</h2>
<ul class="inline-task-list">
<li>Health endpoint returns 200 OK with correct version</li>
<li>All pods running and passing readiness probes</li>
<li>Database connectivity confirmed</li>
<li>Primary user workflow executes without errors</li>
<li>No elevated error rates in application logs</li>
</ul>

<hr/>
<p><em>Generated by AI-Powered CI/CD Platform — {today}</em></p>"""


def create_page(base_url: str, space_key: str, title: str, body: str,
                parent_page_id: str | None = None) -> dict:
    """Create a Confluence page using REST API v1."""
    url = f"{base_url}/wiki/rest/api/content"

    payload = {
        "type": "page",
        "title": title,
        "space": {"key": space_key},
        "body": {
            "storage": {
                "value": body,
                "representation": "storage",
            }
        },
    }

    if parent_page_id:
        payload["ancestors"] = [{"id": parent_page_id}]

    data = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Authorization", get_auth_header())
    req.add_header("Content-Type", "application/json")
    req.add_header("Accept", "application/json")

    try:
        resp = urllib.request.urlopen(req, timeout=30)
        result = json.loads(resp.read())
        print(f"Confluence page created: {result.get('title', title)}")
        page_url = f"{base_url}/wiki{result['_links']['webui']}"
        print(f"URL: {page_url}")
        return result
    except urllib.error.HTTPError as e:
        error_body = e.read().decode()
        print(f"Confluence API error {e.code}: {error_body}", file=sys.stderr)
        raise


def main():
    parser = argparse.ArgumentParser(description="Create Confluence release page")
    parser.add_argument("--version", required=True, help="Version tag")
    parser.add_argument("--product", required=True, help="Product name")
    parser.add_argument("--release-notes-file", required=True, help="Path to release notes")
    parser.add_argument("--space", required=True, help="Confluence space key")
    parser.add_argument("--parent-page-id", default=None, help="Parent page ID")
    args = parser.parse_args()

    base_url = os.environ.get("ATLASSIAN_BASE_URL")
    if not base_url:
        print("ERROR: ATLASSIAN_BASE_URL must be set", file=sys.stderr)
        sys.exit(1)

    print(f"\n=== Confluence Release Page: {args.product} {args.version} ===\n")

    release_notes = read_file(args.release_notes_file)
    title = f"[{args.product}] Release {args.version} — {date.today().isoformat()}"
    body = build_release_page(args.product, args.version, release_notes)

    create_page(base_url, args.space, title, body, args.parent_page_id)
    print(f"\n✅ Confluence release page created for {args.product} {args.version}")


if __name__ == "__main__":
    main()
